### ISSUE TITLE
Build Model Class

### ISSUE THREAD

**Issue by smf541** [smf541/PK-Group5#13]
model object inputs: V_c=1.0, CL=1.0, Ka_q0=1.0
- [x] implement name method
- [x] implement add_compartment( Q_p, V_p) function
- [x] implement list_compartments() function
- [x] implement _ _str_ _ method
- [x] implement _ _len_ _ method
- [x] implement remove( idx ) function
- [x] Merge Model class with its unittests #18

**Comment by alisonfarrar** [comment]
@cosmicnet Moving X to Protocol class. Renaming list() method to list_compartments() to avoid using protected name.
