### ISSUE TITLE
Build Solution Class

### ISSUE THREAD

**Issue by smf541** [smf541/PK-Group5#15]
- [x] implement add( model1, proto1 ) function
- [x] implement list() function
- [x] implement remove ( idx ) function
- [x] implement visualise ( plt_params ) function
- [x] linting issues
- [x] method documentation
- [x] ODE_system method
- [x] solution method
- Takes Model object and Protocol object as input, implements ODE solvers
- Outputs the solution as Matplotlib plots and numpy arrays, accessible via different methods
- User can specify if they want multiple side-by-side plots, or as overlaid plot
- Can implement multiple functions depending on number of solutions being compared
- Plot central compartment only

**Comment by alisonfarrar** [comment]
Notes from James: RE adding side-by-side plotting in Solution.visualise(), possibly restrict visualise to take only one or two pairs of (model, protocol) as input, that way for side-by-side you can just specify the subplots easily
My code was trying to add an arbitrary number of plots, however this is probably too ambitious and we should just get a simple side-by-side functionality as above.
