### ISSUE TITLE
Docs: ReadtheDocs doesn't load / only pulls Protocol class

### ISSUE THREAD

**Issue by alisonfarrar** [smf541/PK-Group5#75]

**Comment by smf541** [comment]
Docs deploy fine locally, including all three modules model, protocol and solution. Currently read the docs doesn't load any documentation at all (even for other packages) so this could be a bug on their side?

**Comment by smf541** [comment]
> Docs deploy fine locally, including all three modules model, protocol and solution. Currently read the docs doesn't load any documentation at all (even for other packages) so this could be a bug on their side?

Correction, it does work for some other packages...

**Comment by smf541** [comment]
Fixed by pull request #83, the problem was missing packages in the requirements.txt file.
